import { CampaignSchema, type Campaign } from "./models";

const seededCampaign: Campaign = {
  id: "campaign.stride-launch",
  name: "Stride / The New Formal",
  brand: "Stride",
  product: "Stride New Formal Collection",
  conceptLine: "Your day changes. Your style should keep up.",
  version: 1,
  status: "active",
  facts: [
    { id: "fact.price.v1", key: "fact.price", label: "Launch price", value: "₹2,499", version: 1, status: "approved", approvedAt: "2026-09-24T10:30:00.000Z" },
    { id: "claim.water-resistant.v1", key: "claim.water-resistant", label: "Weather protection", value: "water-resistant", version: 1, status: "approved", approvedAt: "2026-09-24T10:32:00.000Z" },
    { id: "claim.modular.v1", key: "claim.modular", label: "Collection system", value: "modular layers", version: 1, status: "approved", approvedAt: "2026-09-24T10:33:00.000Z" },
    { id: "claim.capacity.v1", key: "claim.capacity", label: "Collection range", value: "three adaptable looks", version: 1, status: "approved", approvedAt: "2026-09-24T10:34:00.000Z" },
    { id: "claim.recycled-nylon.v1", key: "claim.recycled-nylon", label: "Outerwear material", value: "recycled nylon outer layer", version: 1, status: "approved", approvedAt: "2026-09-24T10:35:00.000Z" },
    { id: "claim.waterproof.v1", key: "claim.waterproof", label: "Prohibited claim", value: "completely waterproof", version: 1, status: "prohibited", approvedAt: null },
  ],
  claims: [
    { id: "approved.water-resistant", factId: "claim.water-resistant.v1", wording: "water-resistant", approvalStatus: "approved", evidence: "Supplier test: coated outer layer resisted light rain for 30 minutes." },
    { id: "approved.modular", factId: "claim.modular.v1", wording: "modular layers", approvalStatus: "approved", evidence: "Three interchangeable styling layers in the production specification." },
    { id: "approved.capacity", factId: "claim.capacity.v1", wording: "three adaptable looks", approvalStatus: "approved", evidence: "Verified campaign styling plan and collection line sheet." },
    { id: "approved.recycled", factId: "claim.recycled-nylon.v1", wording: "recycled nylon outer layer", approvalStatus: "approved", evidence: "GRS-certified outerwear supplier record." },
    { id: "prohibited.waterproof", factId: "claim.waterproof.v1", wording: "completely waterproof", approvalStatus: "prohibited", evidence: "No submersion or waterproof-seam test is approved." },
  ],
  brandRules: [
    { id: "brand.tone", label: "Voice", value: "Assured, useful, premium", type: "tone" },
    { id: "brand.ink", label: "Ink", value: "#1D1C18", type: "colour" },
    { id: "brand.vermilion", label: "Signal", value: "#E84B32", type: "colour" },
    { id: "brand.moss", label: "Approval", value: "#6F7D49", type: "colour" },
    { id: "brand.font", label: "Display type", value: "Editorial serif", type: "font" },
    { id: "brand.cta", label: "Primary CTA", value: "Meet your everyday system", type: "cta" },
    { id: "brand.launch", label: "Launch date", value: "2026-10-12", type: "date" },
  ],
  concepts: [
    {
      id: "concept.context-shift",
      title: "Your day changes. Your style should keep up.",
      promise: "One considered wardrobe moves cleanly through street, studio, and runway.",
      metaphor: "The setting changes while one point of view stays unmistakable.",
      hook: "Three contexts. One uninterrupted move.",
      contentPlan: ["12-second context-shift reel", "Four-part feature proof", "Founder-style design story"],
      selected: true,
    },
    {
      id: "concept.less-repacking",
      title: "Dress once. Move differently.",
      promise: "Modular styling removes the friction of changing identity between roles.",
      metaphor: "A day visualised as one continuous runway.",
      hook: "What if changing plans didn’t mean changing who you are?",
      contentPlan: ["Look transformation reel", "Layer-by-layer carousel", "Design-led launch note"],
      selected: false,
    },
  ],
  assets: [
    {
      id: "asset.reel",
      title: "Context Shift Reel",
      platform: "Instagram",
      format: "12 sec · 9:16",
      role: "Make versatility visceral",
      blocks: [
        { id: "reel.scene.desk", label: "00–03s · Street", type: "scene", content: "Elevator doors part. Stride enters in quiet navy tailoring.", locked: false },
        { id: "reel.scene.transit", label: "03–07s · Studio", type: "scene", content: "The modular layers sharpen into emerald evening form.", template: "The {{value}} sharpen into a new silhouette in the studio.", locked: false },
        { id: "reel.scene.weekend", label: "07–10s · Runway", type: "scene", content: "Three adaptable looks become one uninterrupted point of view.", template: "{{value}} become one uninterrupted point of view.", locked: false },
        { id: "reel.price", label: "10–12s · End card", type: "copy", content: "Launch at ₹2,499 · Meet your everyday system", template: "Launch at {{value}} · Meet your everyday system", maxCharacters: 64, locked: false },
        { id: "reel.product", label: "Locked campaign photography", type: "image", content: "Stride editorial triptych · navy / emerald / oxblood", locked: true, integrityHash: "sha256:8bf7c4a-stride-fashion-locked" },
      ],
    },
    {
      id: "asset.carousel",
      title: "Feature Proof Carousel",
      platform: "Instagram",
      format: "4 slides · 4:5",
      role: "Turn the promise into proof",
      blocks: [
        { id: "carousel.slide1", label: "Slide 01 · Promise", type: "copy", content: "Your day changes. Your style should keep up.", maxCharacters: 52, locked: false },
        { id: "carousel.slide2", label: "Slide 02 · System", type: "copy", content: "Modular layers. Built around what today becomes.", template: "{{value}}. Built around what today becomes.", maxCharacters: 68, locked: false },
        { id: "carousel.slide3", label: "Slide 03 · Material", type: "copy", content: "A water-resistant recycled nylon outer layer, ready for changing plans.", removalContent: "A water-resistant outer layer, ready for changing plans.", maxCharacters: 82, locked: false },
        { id: "carousel.slide4", label: "Slide 04 · Offer", type: "copy", content: "₹2,499 · Meet your everyday system", template: "{{value}} · Meet your everyday system", maxCharacters: 52, locked: false },
        { id: "carousel.product", label: "Locked campaign photography", type: "image", content: "Stride New Formal editorial", locked: true, integrityHash: "sha256:8bf7c4a-stride-fashion-locked" },
        { id: "carousel.logo", label: "Locked Stride wordmark", type: "logo", content: "STRIDE", locked: true, integrityHash: "sha256:91aa20e-stride-wordmark-locked" },
      ],
    },
    {
      id: "asset.linkedin",
      title: "Design Story Launch Post",
      platform: "LinkedIn",
      format: "Text post · 1:1 visual",
      role: "Build product-design credibility",
      blocks: [
        { id: "linkedin.hook", label: "Opening", type: "copy", content: "Most wardrobes are designed for one version of your day. We started with the opposite idea.", maxCharacters: 120, locked: false },
        { id: "linkedin.story", label: "Design story", type: "copy", content: "Stride moves from an elevator to a red studio to the runway without asking you to trade confidence for comfort.", maxCharacters: 180, locked: false },
        { id: "linkedin.module", label: "Product proof", type: "copy", content: "Its modular layers let one silhouette change energy while the point of view stays unmistakably yours.", template: "Its {{value}} let one silhouette change energy while the point of view stays unmistakably yours.", maxCharacters: 180, locked: false },
        { id: "linkedin.material", label: "Material note", type: "copy", content: "A recycled nylon outer layer keeps the form light, considered, and ready for every day.", removalContent: "A considered outer layer keeps the form light and ready for every day.", maxCharacters: 150, locked: false },
        { id: "linkedin.product", label: "Locked campaign photography", type: "image", content: "Stride tailoring material detail", locked: true, integrityHash: "sha256:8bf7c4a-stride-fashion-locked" },
      ],
    },
  ],
  dependencies: [
    { id: "edge.price.reel", factId: "fact.price.v1", assetId: "asset.reel", blockId: "reel.price", reason: "End card displays the approved launch price." },
    { id: "edge.price.carousel", factId: "fact.price.v1", assetId: "asset.carousel", blockId: "carousel.slide4", reason: "Offer slide displays the approved launch price." },
    { id: "edge.modular.reel", factId: "claim.modular.v1", assetId: "asset.reel", blockId: "reel.scene.transit", reason: "Transit scene demonstrates the approved modular-compartment claim." },
    { id: "edge.modular.carousel", factId: "claim.modular.v1", assetId: "asset.carousel", blockId: "carousel.slide2", reason: "Slide 2 states the approved modular-compartment claim." },
    { id: "edge.modular.linkedin", factId: "claim.modular.v1", assetId: "asset.linkedin", blockId: "linkedin.module", reason: "The design story describes the approved modular system." },
    { id: "edge.capacity.reel", factId: "claim.capacity.v1", assetId: "asset.reel", blockId: "reel.scene.weekend", reason: "Runway scene includes the approved three-look collection range." },
    { id: "edge.water.carousel", factId: "claim.water-resistant.v1", assetId: "asset.carousel", blockId: "carousel.slide3", reason: "Slide 3 states the approved weather-protection wording." },
    { id: "edge.recycled.carousel", factId: "claim.recycled-nylon.v1", assetId: "asset.carousel", blockId: "carousel.slide3", reason: "Slide 3 names the approved shell material." },
    { id: "edge.recycled.linkedin", factId: "claim.recycled-nylon.v1", assetId: "asset.linkedin", blockId: "linkedin.material", reason: "The design story names the approved shell material." },
  ],
  approvals: [
    { id: "approval.reel", assetId: "asset.reel", status: "approved", reviewer: "Mira · Creative lead", updatedAt: "2026-09-25T11:05:00.000Z" },
    { id: "approval.carousel", assetId: "asset.carousel", status: "approved", reviewer: "Mira · Creative lead", updatedAt: "2026-09-25T11:08:00.000Z" },
    { id: "approval.linkedin", assetId: "asset.linkedin", status: "approved", reviewer: "Mira · Creative lead", updatedAt: "2026-09-25T11:12:00.000Z" },
  ],
  revisions: [],
  baselineIntegrity: {
    "reel.product": "sha256:8bf7c4a-stride-fashion-locked",
    "carousel.product": "sha256:8bf7c4a-stride-fashion-locked",
    "carousel.logo": "sha256:91aa20e-stride-wordmark-locked",
    "linkedin.product": "sha256:8bf7c4a-stride-fashion-locked",
  },
};

export function createSeedCampaign(): Campaign {
  return CampaignSchema.parse(structuredClone(seededCampaign));
}
